name: Build arma_webhooks DLL/SO

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Rust toolchains and targets
              run: |
                  rustup update stable
                  rustup target add x86_64-pc-windows-gnu
                  rustup target add x86_64-unknown-linux-gnu

            - name: Install mingw-w64 for Windows cross-compilation
              run: sudo apt-get update && sudo apt-get install -y mingw-w64

            - name: Build Linux x64 .so
              run: cargo build --release --target x86_64-unknown-linux-gnu

            - name: Build Windows x64 .dll
              run: cargo build --release --target x86_64-pc-windows-gnu

            - name: Rename output files
              run: |
                  mkdir -p output
                  cp target/x86_64-unknown-linux-gnu/release/libarma_webhooks.so output/arma_webhooks_x64.so
                  cp target/x86_64-pc-windows-gnu/release/arma_webhooks.dll output/arma_webhooks_x64.dll

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: arma_webhooks_binaries
                  path: output/
